#!/usr/bin/env python3
"""Regenerate projects/art-generate.yaml for the Cthulhuquarium asset set.

WHY THIS EXISTS. The queue used to be hand-written, which meant every fish
prompt lived twice: once in the cthulhuquarium repo's fish/*.yaml (the canonical
bible) and once copied into the queue. The copies drifted the moment the art
direction changed -- 2026-08-25, all 23 bible prompts were rewritten from
silhouette-forward to cartoon and the queue still held the old ones, so a rerun
would have regenerated exactly the photorealistic renders Silas rejected. Fish
prompts are now READ from the bible and never retyped.

Non-fish assets (characters, backgrounds, set pieces, screens) have no bible
entry, so their prompts live in this file. That is the one place to edit them.

Usage:
    python scripts/build_cthulhuquarium_art_queue.py [--bible PATH] [--check]

--check exits 1 if the committed queue does not match what this script would
write, which is how a bible edit that nobody propagated gets caught.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
QUEUE = REPO / "projects" / "art-generate.yaml"
# The bible lives in a sibling checkout, whose location differs between a local
# clone and a remote session container, so look in both rather than guessing one.
BIBLE_CANDIDATES = (
    REPO.parent / "cthulhuquarium" / "fish",
    Path.home() / "cthulhuquarium" / "fish",
    Path("/home/user/cthulhuquarium/fish"),
)


def default_bible():
    for path in BIBLE_CANDIDATES:
        if path.is_dir():
            return path
    return BIBLE_CANDIDATES[0]

ENGINE = "krea2"
SQUARE = "1024x1024"
WIDE = "1344x768"
PORTRAIT = "768x1024"

HEADER = """\
# Cthulhuquarium full asset queue -- cthulhuquarium/t-005 + t-015.
#
# GENERATED by scripts/build_cthulhuquarium_art_queue.py. Do not hand-edit the
# fish entries: their prompts are read from the cthulhuquarium repo's fish/*.yaml,
# which is the canonical bible. Edit a prompt THERE and regenerate. Non-fish
# prompts (characters, backgrounds, set pieces, screens) live in the script.
#
# engine: krea2 explicitly on every entry. krea2 came back online 2026-08-24 once
# Silas remounted the model share on the LAN IP (t-033), and a side-by-side against
# flux/schnell on the same prompt was decisively better for this project's look.
# Explicit anyway, so a future default change cannot silently swap the house style.
#
# ART DIRECTION, corrected twice on 2026-08-25.
#
# First correction: the opening batch of ten came back as competent deep-sea
# nature photography -- Silas: "they almost all look like real animals, not
# misshapen horrors from the deep with a cartoonish playfulness." The cause was
# the prompts, not the seeds: dark, low-detail, rim-lit language reads to krea2 as
# "underwater photograph".
#
# Second correction, and the one that holds: the fix for that was a shared style
# suffix ending "NOT photorealistic, not a photograph", which is worse than
# useless. Krea 2 has no instruction-following layer and its negative prompt is
# inert at cfg 1, so that clause was a POSITIVE prompt containing the word
# "photograph" -- and a single style block repeated across every asset is exactly
# the uniformity that reads as machine-made. Prompts now name a MEDIUM WITH A
# HISTORY instead: a lithograph plate, a trade-catalogue engraving, a hand-tinted
# carte-de-visite. A medium cannot come out as a photograph and nothing has to say
# so, and eight different lineages across the set do not average into one look.
# The lineages and the reasoning are in the cthulhuquarium repo's ART-DIRECTION.md.
"""

# NON-FISH LINEAGES. Species carry a `plate` field in the bible; these do not,
# because they are not specimens -- but they follow the same principle, and for
# the same reason. See the cthulhuquarium repo's ART-DIRECTION.md.
#
# The rule that produced these: name a MEDIUM WITH A HISTORY, never a style
# adjective, and never a negation. Krea 2 has no instruction-following layer and
# its negative prompt is inert at cfg 1 (conductor/ART-PROMPTS.md), so the old
# "NOT photorealistic, not a photograph" tail on every one of these was a positive
# prompt containing the word "photograph". A trade-catalogue engraving cannot come
# out as a photograph and nothing has to say so.

# Backgrounds take the PLAINEST lineage on purpose. They are the one surface every
# plate sits against, and a background with a strong medium of its own would fight
# seventy-four different foregrounds. Matches the bible's `gosse` plate, which is
# apt: the domestic tank is the thing Gosse's readers were building.
BG_STYLE = (
    "hand-coloured lithograph plate from an 1850s natural history book, fine "
    "engraved line under flat hand-laid watercolour washes, period pigments, "
    "visible plate mark, foxed paper, unpeopled frame, the caption space beneath "
    "the image left empty"
)

# Set pieces are things you BUY, so they are drawn the way things you buy were
# drawn: a product plate from a Victorian supplier's catalogue, isolated on white,
# made to sell rather than to describe.
SET_STYLE = (
    "Victorian trade-catalogue engraving of a single product, line engraving with "
    "fine hatched shading, the object alone on bare white paper, drawn to be sold "
    "from a supplier's list, the caption space beneath left empty"
)

# The one photographic lineage in the whole project, and deliberately so. Every
# creature is DRAWN, because specimens were recorded by hand by people who could
# not photograph them. Charlotte and Wilbur could be photographed. Nobody needs to
# notice this.
CHAR_STYLE = (
    "hand-tinted carte-de-visite studio photograph on albumen paper mounted to "
    "card, the sitter posed against a painted studio backdrop, tinting applied by "
    "hand to the cheeks and lips only and left off everywhere else, the long "
    "exposure holding them very still, card mount showing at the edges"
)

# Screens are the same photographic stock as an interior view: a wide plate camera,
# a long exposure, slightly wrong verticals, everything still because it had to be.
SCREEN_STYLE = (
    "interior view on a wide plate camera, albumen print, long exposure with "
    "everything held perfectly still, slightly converging verticals, the far "
    "corners sunk in flat unlit shadow, mounted to card"
)

# (slug-suffix, size, prompt). Order is the order they render in.
NON_FISH = [
    ("char-charlotte-fishmonger", PORTRAIT,
     "a cheerful Victorian aquarium proprietress standing in a bright cluttered "
     "back room, immaculate pressed apron over practical workwear, hair pinned "
     "neatly, hands folded and unmarked, a wide unbothered smile above flat "
     "still eyes, tall tanks of luminous green and magenta water "
     "glowing behind her, warm gold lamplight, " + CHAR_STYLE),
    ("char-wilbur-stint", PORTRAIT,
     "a young Victorian aquarium assistant beside a glowing tank, bespectacled, "
     "thinning shoulder-length hair unevenly cut, rumpled apron over rolled "
     "sleeves, forearms scratched and wrapped in mismatched bandages, several "
     "fingers missing from both hands, clutching a long net, earnest exhausted "
     "expression looking slightly off camera, teal and magenta tank glow against "
     "warm gold lamplight, " + CHAR_STYLE),

    ("bg-parlour", WIDE,
     "an empty aquarium interior seen head on, luminous jade-green water, bright "
     "pale gravel floor, a few sunken brass ornaments in warm gold, shafts of "
     "turquoise light from above, " + BG_STYLE),
    ("bg-shipwreck", WIDE,
     "an empty aquarium interior seen head on, the ribbed hull of a small sunken "
     "boat resting on bright gravel, trailing ribbons of acid-green weed, "
     "saturated teal water, warm amber light raking across the timbers, " + BG_STYLE),
    ("bg-cathedral", WIDE,
     "an empty aquarium interior seen head on, tall pale stone arches half buried "
     "in bright gravel, drowned columns receding in ranks, saturated violet and "
     "teal water, a bright turquoise shaft of light between the columns, " + BG_STYLE),
    ("bg-abyssal", WIDE,
     "an empty aquarium interior seen head on, deep indigo and violet water, a "
     "faintly glowing pale floor along the bottom edge, a single vivid lime point "
     "of light far back in the dark, very sparse and open, " + BG_STYLE),

    ("set-extra-shelf", SQUARE,
     "a heavy ornate brass and dark wood aquarium shelf bracket, curling "
     "Victorian ironwork, " + SET_STYLE),
    ("set-richer-silt", SQUARE,
     "a small ornate brass canister tipped over and spilling a fine glittering "
     "silt in an arc, " + SET_STYLE),
    ("set-heavier-feed", SQUARE,
     "a dented tin scoop heaped with fat wriggling grubs, each one glossy and "
     "squirming and faintly smiling, " + SET_STYLE),
    ("set-restless-water", SQUARE,
     "a small brass mechanical paddle-wheel aerator mid-turn, ornate Victorian "
     "engineering with visible gears, throwing a spray of bubbles, " + SET_STYLE),
    ("set-coin-collector", SQUARE,
     "a brass clockwork crab automaton with a coin slot in its back and stubby "
     "articulated legs, ornate Victorian mechanism, one googly glass eye larger "
     "than the other, " + SET_STYLE),
    ("set-glass-brush", SQUARE,
     "a long-handled brass and bristle aquarium scraper with a worn wooden grip, "
     "bristles splayed from use, " + SET_STYLE),

    # SIX EGG PLATES -- cthulhuquarium/t-041. An egg is a thing you BUY, so it takes
    # the set-piece lineage rather than a plate of its own. Rarity is carried by
    # ENGRAVED ORNAMENT DENSITY and nothing else: one monotonic ramp from bare shell
    # to solid worked black, so a row of them in the shop sorts itself at a glance,
    # it survives 256px, it needs no colour (which a trade-catalogue engraving does
    # not have), and it is TEXTURE rather than SCALE -- which is what keeps rarity
    # and size the independent dials t-041 requires. A small MYTHIC egg and a large
    # COMMON egg both have to read instantly, and that pair is the whole shop.
    # The wire stand is deliberately identical across all six: it is a product line
    # in a supplier's catalogue, so consistent presentation is the correct answer.
    ("egg-common", SQUARE,
     "a single plain smooth ovoid egg standing upright in a small plain wire stand, a "
     "few light contour lines following its curve and large areas of shell left bare, "
     + SET_STYLE),
    ("egg-uncommon", SQUARE,
     "a single ovoid egg standing upright in a small plain wire stand, three simple "
     "engraved bands running around its width, the shell between the bands left bare, "
     + SET_STYLE),
    ("egg-rare", SQUARE,
     "a single ovoid egg standing upright in a small plain wire stand, the shell "
     "covered in fine dense speckling with one ruled seam running pole to pole, "
     + SET_STYLE),
    ("egg-epic", SQUARE,
     "a single ovoid egg standing upright in a small plain wire stand, the whole shell "
     "worked with engraved ornamental whorls spiralling from the base to the tip, "
     + SET_STYLE),
    ("egg-legendary", SQUARE,
     "a single ovoid egg standing upright in a small plain wire stand, its entire "
     "surface cut into elaborate engraved scrollwork, a raised ornamental collar "
     "around its base, " + SET_STYLE),
    ("egg-mythic", SQUARE,
     "a single ovoid egg standing upright in a small plain wire stand, engraved so "
     "densely that the shell reads as solid black, its form picked out in fine "
     "reserved white line, " + SET_STYLE),

    ("ichthyonomicon", SQUARE,
     "a fat leather-bound ledger lying closed on a wooden desk, tarnished brass "
     "corner fittings and a heavy clasp, cracked spine, a lurid green waterstain "
     "blooming across the cover, warm gold lamplight from the upper left, "
     "hand-tinted carte-de-visite studio photograph on albumen paper mounted to "
     "card, tinting applied by hand to the waterstain alone and left off "
     "everywhere else, the tooling on the cover worn to illegible loops"),

    # THE LAST AQUARIUM -- cthulhuquarium/t-039. A set piece, because it is a
    # thing you buy, and the most expensive one in the game. Same
    # trade-catalogue engraving as every other purchasable: Charlotte sells it
    # cheerfully and without comment, and the shop plate must not wink.
    ("set-last-aquarium", SQUARE,
     "an enormous ornate aquarium tank with a heavy moulded brass frame and "
     "bevelled glass, scrollwork at every corner, standing empty on a plinth, "
     "far larger than the plate can comfortably hold, " + SET_STYLE),

    ("screen-shop", WIDE,
     "the interior of a cluttered Victorian aquarium supply shop seen head on, "
     "wooden shelves crowded with small tanks glowing green and magenta and brass "
     "instruments, warm gold lamplight, an empty counter across the foreground, "
     "unpeopled, " + SCREEN_STYLE),
    # THE FINALE -- cthulhuquarium/t-039. Deliberately the SAME albumen interior
    # stock as screen-shop and screen-bestiary. That is the whole trick: the
    # medium does not change, the vantage does. The player has spent the game
    # looking at rooms photographed exactly like this one, and t-014's browsable
    # public aquariums already had them "looking in someone's window" from day
    # one. The finale is realising the view goes both ways, so it must not be
    # signalled by a change of register.
    #
    # The eye MOVES rather than stares -- it drifts past and pauses the way you
    # pause at a tank you have already seen today, and moves on. Being stared at
    # is frightening; being unremarkable is worse, and that is the note this
    # whole game has been playing. Hence "mid-drift" and "incurious" in the
    # prompt: a fixed staring eye is the wrong image and the easy one.
    #
    # The window is NOT the door. The door stays closed all game and is never
    # opened, because it was never the way out.
    ("screen-finale", WIDE,
     "the same cluttered Victorian aquarium shop interior seen from further "
     "back and slightly below, its wooden shelves and glowing tanks small in "
     "the middle distance, a broad pane of glass across the whole foreground "
     "with a soft bloom of light on it, and beyond the pane an enormous eye "
     "mid-drift and incurious, filling the upper frame, warm gold lamplight "
     "inside and cooler light outside, unpeopled, " + SCREEN_STYLE),

    ("screen-bestiary", WIDE,
     "a study wall covered edge to edge in framed specimen plates and pinned "
     "cards, dark wood panelling, warm gold lamplight, an empty desk surface "
     "across the foreground, unpeopled, the pinned cards' handwriting worn to "
     "illegible loops, " + SCREEN_STYLE),
]


def load_fish(bible: Path):
    if not bible.is_dir():
        sys.exit(
            f"fish bible not found at {bible}. Clone silasfelinus/cthulhuquarium "
            f"and pass --bible <repo>/fish, or run this from a session that has it."
        )
    fish = []
    for path in sorted(bible.glob("*.yaml")):
        doc = yaml.safe_load(path.read_text(encoding="utf-8"))
        prompt = " ".join((doc.get("art_prompt") or "").split())
        if not prompt:
            sys.exit(f"{path.name} has no art_prompt")
        fish.append((doc["slug"], prompt))
    if not fish:
        sys.exit(f"no species found in {bible}")
    return fish


def wrap(text: str, indent: str, width: int = 96):
    """Fold a prompt onto continuation lines. Plain scalar, so no quoting games."""
    words, lines, cur = text.split(), [], ""
    for w in words:
        cand = f"{cur} {w}".strip()
        if len(indent) + len(cand) > width and cur:
            lines.append(cur)
            cur = w
        else:
            cur = cand
    if cur:
        lines.append(cur)
    return lines


def render(fish, non_fish):
    out = [HEADER, "batch:", "  entries:"]
    entries = [(f"fish-{slug}", SQUARE, prompt) for slug, prompt in fish]
    entries += [(name, size, " ".join(p.split())) for name, size, p in non_fish]
    for name, size, prompt in entries:
        out.append("  - project: cthulhuquarium")
        out.append(f"    engine: {ENGINE}")
        out.append(f"    size: {size}")
        out.append(f"    image_path: projects/process/cthulhuquarium-{name}.webp")
        lines = wrap(prompt, "      ")
        out.append(f"    prompt: {lines[0]}")
        for line in lines[1:]:
            out.append(f"      {line}")
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--bible", type=Path, default=None)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    text = render(load_fish(args.bible or default_bible()), NON_FISH)

    # Parse what we just wrote before trusting it -- a queue that does not load
    # is a silent no-render, which is how this project loses a day.
    doc = yaml.safe_load(text)
    n = len(doc["batch"]["entries"])
    # Guard the direction, not the vocabulary. "silhouette-forward" and
    # "silhouetted" name the rejected style; a shoal that forms "the silhouette
    # of one much larger fish" is a composition and perfectly fine, so the first
    # draft of this check (any use of the word) was a false positive on
    # tithe-shoal. The two checks that matter now are below: no negations at all,
    # and a named medium on every single prompt.
    for e in doc["batch"]["entries"]:
        assert e["prompt"].strip(), e["image_path"]
        assert not re.search(r"silhouette-forward|silhouetted", e["prompt"], re.I), (
            f"{e['image_path']} asks for the silhouette-forward style -- that is the "
            f"direction that produced the rejected photorealistic batch"
        )
        # REVERSED 2026-08-25, then widened the same day. This assertion used to
        # REQUIRE "not photorealistic" on every prompt, which was backwards:
        # conductor/ART-PROMPTS.md is explicit that Krea 2 has no instruction-
        # following layer and its negative prompt is inert at cfg 1, so the clause
        # was a positive prompt containing the word "photorealistic" -- a fair
        # explanation for the first batch coming back as nature photography.
        #
        # The reversal was first written to ban only negations of STYLE words, and
        # that was still too narrow: it let "no face at all" and "no midtones and no
        # wash" through the fish bible untouched (27 files). Krea renders the nouns
        # and drops the negation, so "no face" is how you order a face. There is
        # nothing worth saying in a prompt with a negation -- say what IS there.
        # Matches cthulhuquarium/scripts/validate_fish.py, deliberately.
        neg = re.search(r"\b(?:not|no|without|avoid|never|nor|none|neither|"
                        r"instead\s+of|rather\s+than|lacking|devoid\s+of|free\s+of|"
                        r"absent)\b", e["prompt"], re.I)
        assert not neg, (
            f"{e['image_path']} contains a negation ({neg.group(0)!r}). Krea 2 renders "
            f"the nouns and drops the negation, so this asks for the thing you meant "
            f"to exclude. Describe what IS there -- a medium, an unpeopled frame, an "
            f"empty caption strip (ART-DIRECTION.md rule 2)."
        )
        # One marker per plate lineage, plus the three non-fish media. `haeckel`
        # is matched on "ornamental" -- it was the one this guard caught on its
        # first run, which is the guard doing its job.
        assert re.search(r"lithograph|engraving|carte-de-visite|albumen|rubbing|"
                         r"cigarette card|scraperboard|risograph|glass model|"
                         r"specimen|ornamental",
                         e["prompt"], re.I), (
            f"{e['image_path']} names no medium. Every prompt must carry a lineage "
            f"(ART-DIRECTION.md), not a style adjective."
        )

    if args.check:
        current = QUEUE.read_text(encoding="utf-8") if QUEUE.exists() else ""
        if current != text:
            print("art-generate.yaml is stale -- rerun without --check", file=sys.stderr)
            return 1
        print(f"art-generate.yaml up to date ({n} entries)")
        return 0

    QUEUE.write_text(text, encoding="utf-8")
    print(f"wrote {QUEUE.relative_to(REPO)} ({n} entries, all pending)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
