#!/usr/bin/env python3
"""
build_status.py — Regenerate STATUS.md from projects/*/roadmap.yaml and pitches/*.md

Run from repo root: python scripts/build_status.py
"""

import os
import re
import yaml
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
PROJECTS_DIR = REPO_ROOT / "projects"
PITCHES_DIR = REPO_ROOT / "pitches"
STATUS_FILE = REPO_ROOT / "STATUS.md"

STATUS_COLS = ["ready", "waiting", "claimed", "review", "done", "blocked", "needs-human"]


def load_roadmap(project_dir: Path) -> dict | None:
    roadmap = project_dir / "roadmap.yaml"
    if not roadmap.exists():
        return None
    with open(roadmap) as f:
        return yaml.safe_load(f)


def compute_progress(milestones: list[dict]) -> float:
    if not milestones:
        return 0.0
    total = sum(m.get("weight", 10) for m in milestones)
    done = sum(
        m.get("weight", 10) * (1.0 if m.get("status") == "done" else 0.5 if m.get("status") == "in-progress" else 0.0)
        for m in milestones
    )
    return round(done / total * 100, 1) if total else 0.0


def count_tasks(tasks: list[dict]) -> dict[str, int]:
    counts = {s: 0 for s in STATUS_COLS}
    for t in tasks:
        s = t.get("status", "ready")
        if s in counts:
            counts[s] += 1
    return counts


def get_pitches_pending() -> list[tuple[str, str, str]]:
    """Returns (title, date, project_target) for pitches with status awaiting-silas."""
    results = []
    if not PITCHES_DIR.exists():
        return results
    for f in sorted(PITCHES_DIR.glob("*.md")):
        if f.name == "README.md":
            continue
        text = f.read_text()
        title = re.search(r"^#\s*Pitch:\s*(.+)$", text, re.MULTILINE)
        title = title.group(1).strip() if title else f.stem
        date_match = re.match(r"(\d{4}-\d{2}-\d{2})-", f.name)
        date = date_match.group(1) if date_match else "unknown"
        status_match = re.search(r"^status:\s*(\S+)", text, re.MULTILINE)
        status = status_match.group(1).strip().rstrip("#").strip() if status_match else "awaiting-silas"
        target_match = re.search(r"^project-target:\s*(.+)$", text, re.MULTILINE)
        target = target_match.group(1).strip() if target_match else "—"
        if "awaiting" in status:
            results.append((title, date, target))
    return results


def build_status():
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    project_rows = []
    global_counts = {s: 0 for s in STATUS_COLS}
    active_projects = 0

    for project_dir in sorted(PROJECTS_DIR.iterdir()):
        if not project_dir.is_dir() or project_dir.name.startswith("_"):
            continue
        roadmap = load_roadmap(project_dir)
        if not roadmap:
            continue

        active_projects += 1
        milestones = roadmap.get("milestones") or []
        tasks = roadmap.get("tasks") or []
        kind = roadmap.get("kind", "software")
        progress = compute_progress(milestones)
        counts = count_tasks(tasks)

        for k, v in counts.items():
            global_counts[k] += v

        project_rows.append(
            f"| {project_dir.name} | {kind} | {progress}% "
            f"| {counts['ready']} | {counts['done']} | {counts['blocked']} |"
        )

    pitches = get_pitches_pending()
    pitch_rows = [f"| {t} | {d} | {p} |" for t, d, p in pitches]

    lines = [
        "# STATUS.md — Auto-generated project snapshot",
        f"<!-- Generated by scripts/build_status.py — DO NOT EDIT BY HAND -->",
        f"<!-- Last generated: {now} -->",
        "",
        "> This file is regenerated each cycle. Edit `CONTROL.md` to steer; edit `projects/*/roadmap.yaml` to update task state.",
        "",
        "## Global",
        "",
        "| Metric | Value |",
        "|---|---|",
        f"| Active projects | {active_projects} |",
        f"| Total tasks | {sum(global_counts.values())} |",
        f"| Ready | {global_counts['ready']} |",
        f"| In progress (claimed/review) | {global_counts['claimed'] + global_counts['review']} |",
        f"| Needs human | {global_counts['needs-human']} |",
        f"| Blocked | {global_counts['blocked']} |",
        f"| Pitches pending | {len(pitches)} |",
        "",
        "## Projects",
        "",
        "| Project | Kind | Progress | Ready | Done | Blocked |",
        "|---|---|---|---|---|---|",
        *project_rows,
        "",
        "## Pitches awaiting vote",
        "",
        "| Pitch | Date | Target |",
        "|---|---|---|",
        *(pitch_rows if pitch_rows else ["| (none) | — | — |"]),
    ]

    STATUS_FILE.write_text("\n".join(lines) + "\n")
    print(f"STATUS.md written ({len(project_rows)} projects, {len(pitches)} pitches)")


if __name__ == "__main__":
    build_status()
