#!/usr/bin/env python3
"""Regenerate projects/art-generate.yaml for the Cthulhuquarium asset set.

WHY THIS EXISTS. The queue used to be hand-written, which meant every fish
prompt lived twice: once in the cthulhuquarium repo's fish/*.yaml (the canonical
bible) and once copied into the queue. The copies drifted the moment the art
direction changed -- 2026-08-25, all 23 bible prompts were rewritten from
silhouette-forward to cartoon and the queue still held the old ones, so a rerun
would have regenerated exactly the photorealistic renders Silas rejected. Fish
prompts are now READ from the bible and never retyped.

Non-fish assets (characters, backgrounds, set pieces, screens) have no bible
entry, so their prompts live in this file. That is the one place to edit them.

Usage:
    python scripts/build_cthulhuquarium_art_queue.py [--bible PATH] [--check]

--check exits 1 if the committed queue does not match what this script would
write, which is how a bible edit that nobody propagated gets caught.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
QUEUE = REPO / "projects" / "art-generate.yaml"
# The bible lives in a sibling checkout, whose location differs between a local
# clone and a remote session container, so look in both rather than guessing one.
BIBLE_CANDIDATES = (
    REPO.parent / "cthulhuquarium" / "fish",
    Path.home() / "cthulhuquarium" / "fish",
    Path("/home/user/cthulhuquarium/fish"),
)


def default_bible():
    for path in BIBLE_CANDIDATES:
        if path.is_dir():
            return path
    return BIBLE_CANDIDATES[0]

ENGINE = "krea2"
SQUARE = "1024x1024"
WIDE = "1344x768"
PORTRAIT = "768x1024"

HEADER = """\
# Cthulhuquarium full asset queue -- cthulhuquarium/t-005 + t-015.
#
# GENERATED by scripts/build_cthulhuquarium_art_queue.py. Do not hand-edit the
# fish entries: their prompts are read from the cthulhuquarium repo's fish/*.yaml,
# which is the canonical bible. Edit a prompt THERE and regenerate. Non-fish
# prompts (characters, backgrounds, set pieces, screens) live in the script.
#
# engine: krea2 explicitly on every entry. krea2 came back online 2026-08-24 once
# Silas remounted the model share on the LAN IP (t-033), and a side-by-side against
# flux/schnell on the same prompt was decisively better for this project's look.
# Explicit anyway, so a future default change cannot silently swap the house style.
#
# ART DIRECTION, corrected 2026-08-25. The first batch of ten came back as
# competent deep-sea nature photography -- Silas: "they almost all look like real
# animals, not misshapen horrors from the deep with a cartoonish playfulness... I
# want creative, colorful, and vibrant monster fish and backgrounds." The cause was
# the prompts, not the seeds: dark, low-detail, rim-lit language reads to krea2 as
# "underwater photograph". Every prompt below now leads with saturated cartoon
# illustration and carries an explicit negative against photorealism, because
# neither engine drops the photographic reading unless told to.
"""

# Backgrounds are what fish are composited ON TOP OF, so they stay readable and
# uncluttered -- but "readable" was previously written as "dark", which is what
# made them photographic. Saturated and empty, not dim and empty.
BG_STYLE = (
    "vibrant saturated cartoon illustration, thick confident outlines, bold "
    "flat colour with glossy highlights, playful macabre storybook, "
    "NOT photorealistic, not a photograph, no creatures, no text"
)
SET_STYLE = (
    "vibrant saturated cartoon object illustration, thick confident outlines, "
    "bold colour, glossy highlights, playful macabre storybook, isolated object "
    "centred on a plain flat background, no background scene, "
    "NOT photorealistic, not a photograph, no text"
)
CHAR_STYLE = (
    "vibrant saturated cartoon character illustration, thick confident outlines, "
    "expressive exaggerated features, bold colour, glossy highlights, playful "
    "macabre storybook, half-length portrait, "
    "NOT photorealistic, not a photograph, no text"
)

# (slug-suffix, size, prompt). Order is the order they render in.
NON_FISH = [
    ("char-charlotte-fishmonger", PORTRAIT,
     "a cheerful Victorian aquarium proprietress standing in a bright cluttered "
     "back room, immaculate pressed apron over practical workwear, hair pinned "
     "neatly, hands folded and unmarked, a wide unbothered smile that does not "
     "quite reach the eyes, tall tanks of luminous green and magenta water "
     "glowing behind her, warm gold lamplight, " + CHAR_STYLE),
    ("char-wilbur-stint", PORTRAIT,
     "a young Victorian aquarium assistant beside a glowing tank, bespectacled, "
     "thinning shoulder-length hair unevenly cut, rumpled apron over rolled "
     "sleeves, forearms scratched and wrapped in mismatched bandages, several "
     "fingers missing from both hands, clutching a long net, earnest exhausted "
     "expression looking slightly off camera, teal and magenta tank glow against "
     "warm gold lamplight, " + CHAR_STYLE),

    ("bg-parlour", WIDE,
     "an empty aquarium interior seen head on, luminous jade-green water, bright "
     "pale gravel floor, a few sunken brass ornaments in warm gold, shafts of "
     "turquoise light from above, " + BG_STYLE),
    ("bg-shipwreck", WIDE,
     "an empty aquarium interior seen head on, the ribbed hull of a small sunken "
     "boat resting on bright gravel, trailing ribbons of acid-green weed, "
     "saturated teal water, warm amber light raking across the timbers, " + BG_STYLE),
    ("bg-cathedral", WIDE,
     "an empty aquarium interior seen head on, tall pale stone arches half buried "
     "in bright gravel, drowned columns receding in ranks, saturated violet and "
     "teal water, a bright turquoise shaft of light between the columns, " + BG_STYLE),
    ("bg-abyssal", WIDE,
     "an empty aquarium interior seen head on, deep indigo and violet water, a "
     "faintly glowing pale floor along the bottom edge, a single vivid lime point "
     "of light far back in the dark, very sparse and open, " + BG_STYLE),

    ("set-extra-shelf", SQUARE,
     "a heavy ornate brass and dark wood aquarium shelf bracket, curling "
     "Victorian ironwork, warm gold metal against a flat teal background, " + SET_STYLE),
    ("set-richer-silt", SQUARE,
     "a small ornate brass canister tipped over and spilling glittering violet "
     "silt in a bright arc, warm gold metal against a flat teal background, " + SET_STYLE),
    ("set-heavier-feed", SQUARE,
     "a dented tin scoop heaped with fat wriggling grubs, each one glossy and "
     "squirming and faintly smiling, warm gold metal against a flat teal "
     "background, " + SET_STYLE),
    ("set-restless-water", SQUARE,
     "a small brass mechanical paddle-wheel aerator mid-turn, ornate Victorian "
     "engineering with visible gears, throwing bright turquoise bubbles, warm "
     "gold metal against a flat teal background, " + SET_STYLE),
    ("set-coin-collector", SQUARE,
     "a brass clockwork crab automaton with a coin slot in its back and stubby "
     "articulated legs, ornate Victorian mechanism, one googly glass eye larger "
     "than the other, warm gold metal against a flat teal background, " + SET_STYLE),
    ("set-glass-brush", SQUARE,
     "a long-handled brass and bristle aquarium scraper with a worn wooden grip, "
     "warm gold metal against a flat teal background, " + SET_STYLE),

    ("ichthyonomicon", SQUARE,
     "a fat leather-bound ledger lying closed on a wooden desk, tarnished brass "
     "corner fittings and a heavy clasp, cracked spine, a lurid green waterstain "
     "blooming across the cover, warm gold lamplight from the upper left and "
     "vivid green tank glow from the right, vibrant saturated cartoon "
     "illustration, thick confident outlines, bold colour, glossy highlights, "
     "playful macabre storybook, NOT photorealistic, not a photograph, "
     "no readable text or lettering anywhere"),

    ("screen-shop", WIDE,
     "the interior of a cluttered Victorian aquarium supply shop seen head on, "
     "wooden shelves crowded with small tanks glowing green and magenta and brass "
     "instruments, warm gold lamplight, an empty counter across the foreground, "
     "no people, " + BG_STYLE),
    ("screen-bestiary", WIDE,
     "a study wall covered edge to edge in framed specimen plates and pinned "
     "cards, dark wood panelling, warm gold lamplight, an empty desk surface "
     "across the foreground, no people, no readable text, " + BG_STYLE),
]


def load_fish(bible: Path):
    if not bible.is_dir():
        sys.exit(
            f"fish bible not found at {bible}. Clone silasfelinus/cthulhuquarium "
            f"and pass --bible <repo>/fish, or run this from a session that has it."
        )
    fish = []
    for path in sorted(bible.glob("*.yaml")):
        doc = yaml.safe_load(path.read_text(encoding="utf-8"))
        prompt = " ".join((doc.get("art_prompt") or "").split())
        if not prompt:
            sys.exit(f"{path.name} has no art_prompt")
        fish.append((doc["slug"], prompt))
    if not fish:
        sys.exit(f"no species found in {bible}")
    return fish


def wrap(text: str, indent: str, width: int = 96):
    """Fold a prompt onto continuation lines. Plain scalar, so no quoting games."""
    words, lines, cur = text.split(), [], ""
    for w in words:
        cand = f"{cur} {w}".strip()
        if len(indent) + len(cand) > width and cur:
            lines.append(cur)
            cur = w
        else:
            cur = cand
    if cur:
        lines.append(cur)
    return lines


def render(fish, non_fish):
    out = [HEADER, "batch:", "  entries:"]
    entries = [(f"fish-{slug}", SQUARE, prompt) for slug, prompt in fish]
    entries += [(name, size, " ".join(p.split())) for name, size, p in non_fish]
    for name, size, prompt in entries:
        out.append("  - project: cthulhuquarium")
        out.append(f"    engine: {ENGINE}")
        out.append(f"    size: {size}")
        out.append(f"    image_path: projects/process/cthulhuquarium-{name}.webp")
        lines = wrap(prompt, "      ")
        out.append(f"    prompt: {lines[0]}")
        for line in lines[1:]:
            out.append(f"      {line}")
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--bible", type=Path, default=None)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    text = render(load_fish(args.bible or default_bible()), NON_FISH)

    # Parse what we just wrote before trusting it -- a queue that does not load
    # is a silent no-render, which is how this project loses a day.
    doc = yaml.safe_load(text)
    n = len(doc["batch"]["entries"])
    # Guard the direction, not the vocabulary. "silhouette-forward" and
    # "silhouetted" name the rejected style; a shoal that forms "the silhouette
    # of one much larger fish" is a composition and perfectly fine, so the first
    # draft of this check (any use of the word) was a false positive on
    # tithe-shoal. What actually matters is that every prompt carries the
    # anti-photoreal negative, since that is the single line standing between
    # this queue and another batch of nature photography.
    for e in doc["batch"]["entries"]:
        assert e["prompt"].strip(), e["image_path"]
        assert not re.search(r"silhouette-forward|silhouetted", e["prompt"], re.I), (
            f"{e['image_path']} asks for the silhouette-forward style -- that is the "
            f"direction that produced the rejected photorealistic batch"
        )
        assert re.search(r"not\s+photorealistic", e["prompt"], re.I), (
            f"{e['image_path']} has no anti-photorealism negative. krea2 defaults to "
            f"nature photography for anything creature-shaped; without this line it "
            f"will hand back exactly what Silas rejected on 2026-08-25."
        )

    if args.check:
        current = QUEUE.read_text(encoding="utf-8") if QUEUE.exists() else ""
        if current != text:
            print("art-generate.yaml is stale -- rerun without --check", file=sys.stderr)
            return 1
        print(f"art-generate.yaml up to date ({n} entries)")
        return 0

    QUEUE.write_text(text, encoding="utf-8")
    print(f"wrote {QUEUE.relative_to(REPO)} ({n} entries, all pending)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
