#!/usr/bin/env python3
"""
generate_changelog.py — Append a per-cycle change summary to CHANGELOG.md.

Reads git log since the last CHANGELOG.md entry (or the past 30 days on first
run), groups commits by conductor project slug based on changed file paths, and
appends a dated section.

Run at the END of every Worker cycle, alongside sync_projects_to_dreams.py.

Format appended to CHANGELOG.md:
  ## YYYY-MM-DD
  - **<slug>**: [t-NNN] commit title
  - **<slug>**: commit title
  ...

Usage: python scripts/generate_changelog.py [--dry-run]
"""

import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
CHANGELOG_FILE = REPO_ROOT / "CHANGELOG.md"
PROJECTS_DIR = REPO_ROOT / "projects"

# Matches t-NNN or t-NNN in commit subject
TASK_ID_RE = re.compile(r"\bt-\d{3,}\b")

# Commits that are noise — skip them
SKIP_SUBJECTS_RE = re.compile(
    r"^(chore: refresh STATUS\.md|Merge (branch|pull request)|chore: merge)",
    re.IGNORECASE,
)


def run(cmd):
    result = subprocess.run(cmd, capture_output=True, text=True, cwd=REPO_ROOT)
    return result.stdout.strip()


def last_changelog_date():
    """Return ISO date string of the most recent ## YYYY-MM-DD header, or None."""
    if not CHANGELOG_FILE.exists():
        return None
    content = CHANGELOG_FILE.read_text()
    dates = re.findall(r"^## (\d{4}-\d{2}-\d{2})", content, re.MULTILINE)
    return dates[-1] if dates else None


def slug_from_paths(paths):
    """Extract conductor project slugs from a list of changed file paths."""
    slugs = set()
    for p in paths:
        # projects/<slug>/... → <slug>
        m = re.match(r"^projects/([^/]+)/", p)
        if m:
            candidate = m.group(1)
            # Skip meta-directories
            if candidate not in ("images", "_template"):
                slugs.add(candidate)
        # scripts/ → conductor
        elif p.startswith("scripts/"):
            slugs.add("conductor")
        # Root files (AGENTS.md, CONTROL.md, etc.) → conductor
        elif "/" not in p and p.endswith((".md", ".yaml", ".yml", ".py")):
            slugs.add("conductor")
    return slugs


def commits_since(since_date):
    """Return list of (subject, [slug, ...]) since ISO date (exclusive)."""
    if since_date:
        since_arg = f"--since={since_date}T23:59:59Z"
    else:
        since_arg = "--since=30 days ago"

    # Get commit hashes in date order (oldest first)
    log_out = run(
        ["git", "log", since_arg, "--no-merges", "--format=%H|%s", "--reverse"]
    )
    if not log_out:
        return []

    entries = []
    for line in log_out.splitlines():
        if "|" not in line:
            continue
        sha, subject = line.split("|", 1)
        if SKIP_SUBJECTS_RE.match(subject.strip()):
            continue
        # Get changed files for this commit
        files_out = run(["git", "diff-tree", "--no-commit-id", "-r", "--name-only", sha])
        paths = [f.strip() for f in files_out.splitlines() if f.strip()]
        slugs = slug_from_paths(paths)
        if slugs:
            entries.append((subject.strip(), sorted(slugs)))

    return entries


def build_section(entries, today):
    if not entries:
        return None

    # Group by slug, preserving per-slug bullet order
    slug_lines = {}
    for subject, slugs in entries:
        task_ids = TASK_ID_RE.findall(subject)
        prefix = f"[{', '.join(task_ids)}] " if task_ids else ""
        bullet = f"{prefix}{subject}"
        for slug in slugs:
            slug_lines.setdefault(slug, []).append(bullet)

    lines = [f"## {today}"]
    for slug in sorted(slug_lines):
        for bullet in slug_lines[slug]:
            lines.append(f"- **{slug}**: {bullet}")
    lines.append("")

    return "\n".join(lines)


def main():
    dry_run = "--dry-run" in sys.argv

    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    last_date = last_changelog_date()

    if last_date == today:
        print(f"CHANGELOG.md already has a {today} entry — nothing to append.")
        return

    entries = commits_since(last_date)
    section = build_section(entries, today)

    if section is None:
        print("No new project commits found — CHANGELOG.md unchanged.")
        return

    if dry_run:
        print("--- DRY RUN ---")
        print(section)
        return

    header = "# CHANGELOG\n\nPer-cycle change summary. Generated by scripts/generate_changelog.py.\n\n"
    if CHANGELOG_FILE.exists():
        existing = CHANGELOG_FILE.read_text()
        # Insert new section after the top-level header block
        if existing.startswith("# CHANGELOG"):
            # Find where the first ## section starts
            match = re.search(r"^## ", existing, re.MULTILINE)
            if match:
                insert_at = match.start()
                new_content = existing[:insert_at] + section + "\n" + existing[insert_at:]
            else:
                new_content = existing.rstrip("\n") + "\n\n" + section
        else:
            new_content = existing.rstrip("\n") + "\n\n" + section
    else:
        new_content = header + section

    CHANGELOG_FILE.write_text(new_content)
    print(f"CHANGELOG.md updated — appended {today} section.")


if __name__ == "__main__":
    main()
